/* eslint-disable @next/next/no-img-element */
import React from 'react'
import PlanYourBookComp from '@/screens/publish/plan-your-book/PlanYourBookComp';


export const metadata = {
    title: "Plan Your Book: Print Book and Ebook | IngramPublishers",
    description: "Generated by create next app",
    icons: {
        icon: '/IngramLogo.png'
    }
};

const PlanYourBook = () => {
    return (
        <PlanYourBookComp />
    )
}

export default PlanYourBook