import HomeComp from '@/pages/home/HomeComp'

export const metadata = {
    title: "IngramPublishers: Self-Publishing Book Company | Print & Distribute ",
    description: "Generated by create next app",
    icons: {
        icon: '/IngramFavIcon.png'
    }
};

async function home() {
    return (
        <HomeComp />
    )
}

export default home 