import React from 'react'
import HowToSelfPublishComp from '@/screens/publish/how-to-self-publish/HowToSelfPublishComp';

export const metadata = {
    title: "How to Self Publish a Book",
    description: "Generated by create next app",
    icons: {
        icon: '/IngramLogo.png'
    }
};

const HowToSelfPublish = () => {

    return (
        <HowToSelfPublishComp />
    )
}

export default HowToSelfPublish