/* eslint-disable react/no-unescaped-entities */
import PublishHeroBanner from '@/components/PublishHeroBanner'
import Image from 'next/image';
import React from 'react'
import HowItWorksComp from '@/pages/publish/how-it-works/HowItWorksComp';

export const metadata = {
    title: "How it Works: Publish Like a Pro | IngramPublishers",
    description: "Generated by create next app",
    icons: {
        icon: '/IngramLogo.png'
    }
};

const HowItWorks = () => {
    return (
        <>
            <HowItWorksComp />
        </>
    )
}

export default HowItWorks